# Generated by Django 5.2.1 on 2025-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
